import type { Product } from "./catalog";

export const products: Product[] = [
  {
    slug: "essential-sorbents-joint-comfort",
    name: "Essential Sorbents - Joint Comfort",
    brand: "Essential Sorbents",
    categorySlugs: [
      "essential-sorbents-lymphosan",
      "detoks-i-ciscenje-organizma",
      "elasticni-zglobovi",
      "anti-age-proizvode",
      "cvrste-kosti",
    ],
    shortDescription:
      "Essential Sorbents - Joint Comfort mešavina za pripremu detoks koktela sa hondroprotektivnim komponentama pomaže u efikasnom čišćenju tela i zaštiti zglobova",
    image: "/products/essential-sorbents-joint-comfort.png",
    price: 1200,
  },
  {
    slug: "pulse-box-snazno-srce",
    name: "PULSE BOX - Snažno srce",
    brand: "Daily Box",
    categorySlugs: [
      "daily-box",
      "zdravo-srce",
      "suplementi-za-energiju-i-fokus",
      "duga-mladost",
    ],
    shortDescription:
      "PULSE BOX – Snažno srce trostepena zaštita kardiovaskularnog sistema za svakog savremenog čoveka: održavanje ćelijske regeneracije",
    image: "/products/pulse-box-snazno-srce.png",
    price: 3200,
  },
  {
    slug: "renaissance-triple-set",
    name: "Renaissance Triple Set",
    brand: "Renaissance Triple Set",
    categorySlugs: [
      "renaissance-triple-set",
      "suplementi-za-energiju-i-fokus",
      "detoks-i-ciscenje-organizma",
      "elasticni-zglobovi",
      "duga-mladost",
      "suplementi-za-zeludac-i-creva",
      "suplementi-za-jetru",
      "zdravi-bubrezi",
      "zdravo-srce",
      "suplementi-za-vid",
      "prevencija-alergija",
      "prevencija-dijabetesa",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Renaissance Triple Set – je potpuno nov sistem trostruke podrške razmene materija, metabolizma energije i štiti ćelije od oksidacije",
    image: "/products/renaissance-triple-set.png",
    price: 5900,
  },
  {
    slug: "synchrovitals-iv-hronobioloska-zastita-jetre",
    name: "Synchrovitals IV - Hronobiološka zaštita jetre",
    brand: "Synchrovitals",
    categorySlugs: ["synchrovitals", "suplementi-za-jetru"],
    shortDescription:
      "Synchrovitals IV - Hronobiološka zaštita jetre dvofazni kompleks na bazi hepatoprotektivnih biljnih ekstrakata šarenog čkalja, korena srčenjaka",
    image: "/products/synchrovitals-iv-hronobioloska-zastita-jetre.png",
    price: 1750,
  },
  {
    slug: "renaissance-triple-set-formula-3",
    name: "Renaissance Triple Set - Formula 3",
    brand: "Renaissance Triple Set",
    categorySlugs: [
      "renaissance-triple-set",
      "anti-age-proizvode",
      "suplementi-za-energiju-i-fokus",
      "elasticni-zglobovi",
      "suplementi-za-zeludac-i-creva",
      "suplementi-za-jetru",
      "zdravi-bubrezi",
      "zdravo-srce",
      "suplementi-za-vid",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Renaissance Triple Set - Formula 3 legendarni kompleks, koji je nastavak detoks serije „Poreklo čistoće“, obuhvata najvažnije biljne ekstrakte, minerale",
    image: "/products/renaissance-triple-set-formula-3.png",
    price: 5500,
  },
  {
    slug: "synchrovitals-iii-hronobioloska-zastita-srca",
    name: "Synchrovitals III - Hronobiološka zaštita srca",
    brand: "Synchrovitals",
    categorySlugs: ["synchrovitals", "zdravo-srce", "suplementi-za-energiju-i-fokus"],
    shortDescription:
      "Synchrovitals III - Hronobiološka zaštita srca dvofazni kardioprotektivni kompleks na bazi beta-glukana ovsa, Alfa-lipoinske kiseline, selena, likopena",
    image: "/products/synchrovitals-iii-hronobioloska-zastita-srca.png",
    price: 3300,
  },
  {
    slug: "formula-4-n-v-m-n",
    name: "Formula 4 N.V.M.N",
    brand: "Novomin",
    categorySlugs: [
      "novomin",
      "anti-age-proizvode",
      "suplementi-za-energiju-i-fokus",
      "duga-mladost",
      "suplementi-za-jetru",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Formula 4 N.V.M.N sadrži kompleks s vitaminima  A,C,E , skoro 20 godina se smatra da je to jedna od najjačih antioksidantnih formula.",
    image: "/products/formula-4-n-v-m-n.png",
    price: 2400,
  },
  {
    slug: "glucosamine-and-chondroitin-fitness-catalyst",
    name: "Glucosamine and Chondroitin - Fitness Catalyst",
    brand: "Fitness Catalyst",
    categorySlugs: ["fitness-catalyst", "elasticni-zglobovi"],
    shortDescription:
      "Glucosamine and Chondroitin - Fitness Catalyst maksimalna podrška zglobovima.",
    image: "/products/glucosamine-and-chondroitin-fitness-catalyst.png",
    price: 4900,
  },
  {
    slug: "essential-minerals-iodine-with-siberian-herbs",
    name: "Essential Minerals - Iodine with Siberian herbs",
    brand: "Essential Minerals Elemvitals",
    categorySlugs: [
      "essential-minerals-elemvitals",
      "anti-age-proizvode",
      "suplementi-za-energiju-i-fokus",
      "duga-mladost",
      "prevencija-dijabetesa",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Essential Minerals - Iodine with Siberian herbs, kompleks sa visoko bioraspoloživim organskim jodom iz ekstrakta fukusa i prirodnim adaptogenom",
    image: "/products/essential-minerals-iodine-with-siberian-herbs.png",
    price: 1400,
  },
  {
    slug: "set-pomoc-za-zglobove-ujan-nomo-balzam-sirokog-spektra-koren",
    name: "Set pomoć za zglobove - Ujan Nomo + Balzam širokog spektra Koren",
    brand: "Sibirski balzami",
    categorySlugs: ["sibirski-balzami"],
    shortDescription:
      "Set pomoć za zglobove čine: Ujan Nomo Balzam za telo i Balzam širokog spektra Koren.",
    image: "/products/set-pomoc-za-zglobove-ujan-nomo-balzam-sirokog-spektra-koren.png",
    price: 2150,
  },
  {
    slug: "ujan-nomo-balzam-za-telo",
    name: "Ujan Nomo Balzam za telo",
    brand: "Sibirski balzami",
    categorySlugs: ["sibirski-balzami", "elasticni-zglobovi"],
    shortDescription:
      "Ujan Nomo Balzam za telo značajno poboljšava kretanje, pružajući trenutni osećaj hlađenja i olakšanja od upala.",
    image: "/products/ujan-nomo-balzam-za-telo.png",
    price: 900,
  },
  {
    slug: "essential-minerals-iron-with-siberian-herbs",
    name: "Essential Minerals - Iron with Siberian herbs",
    brand: "Essential Minerals Elemvitals",
    categorySlugs: [
      "essential-minerals-elemvitals",
      "anti-age-proizvode",
      "suplementi-za-energiju-i-fokus",
      "duga-mladost",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Essential Minerals - Iron with Siberian herbs kompleks sa bioraspoloživim organskim gvožđem poboljšava zasićenje organizma kiseonikom",
    image: "/products/essential-minerals-iron-with-siberian-herbs.png",
    price: 1900,
  },
  {
    slug: "essential-mineral-calcium-with-siberian-herbs",
    name: "Essential Mineral - Calcium with Siberian herbs",
    brand: "Essential Minerals Elemvitals",
    categorySlugs: [
      "essential-minerals-elemvitals",
      "cvrste-kosti",
      "suplementi-za-energiju-i-fokus",
    ],
    shortDescription:
      "Essential Mineral - Calcium with Siberian herbs kompleks sa prirodnim kalcijumom, obogaćen vitaminom D3, prirodnim silicijumom iz ekstrakta rastavića",
    image: "/products/essential-mineral-calcium-with-siberian-herbs.png",
    price: 1400,
  },
  {
    slug: "essential-minerals-selenium-with-siberian-herbs",
    name: "Essential Minerals - Selenium with Siberian herbs",
    brand: "Essential Minerals Elemvitals",
    categorySlugs: [
      "essential-minerals-elemvitals",
      "anti-age-proizvode",
      "antistres-zastita",
      "duga-mladost",
      "zdravo-srce",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Essential Minerals. Selenium with Siberian herbs kompleks sa visoko bioraspoloživim organskim selenom, obogaćen vitaminima i biljnim ekstraktima",
    image: "/products/essential-minerals-selenium-with-siberian-herbs.png",
    price: 2200,
  },
  {
    slug: "essential-botanics-ginkgo-i-baikal-skullcap",
    name: "Essential Botanics - Ginkgo&Baikal Skullcap",
    brand: "Essential Botanics",
    categorySlugs: ["essential-botanics"],
    shortDescription:
      "Essential Botanics - Ginkgo&Baikal Skullcap biljni kompleks na bazi ginko bilobe, Gotu kole i bajkalske kapice - prirodna formula ciljanog delovanja",
    image: "/products/essential-botanics-ginkgo-i-baikal-skullcap.png",
    price: 1100,
  },
  {
    slug: "essential-botanics-bearberry-i-lingonberry",
    name: "Essential Botanics - Bearberry&Lingonberry",
    brand: "Essential Botanics",
    categorySlugs: ["essential-botanics", "zdravi-bubrezi"],
    shortDescription:
      "Essential Botanics - Bearberry&Lingonberry biljna formula na bazi ekstrakta medveđe bobice i rena sa listovima i plodom brusnice sprečava stagnaciju tečnosti",
    image: "/products/essential-botanics-bearberry-i-lingonberry.png",
    price: 920,
  },
  {
    slug: "essential-botanics-valerian-i-melissa",
    name: "Essential Botanics - Valerian&Melissa",
    brand: "Essential Botanics",
    categorySlugs: ["essential-botanics", "celicni-nervi", "antistres-zastita"],
    shortDescription:
      "Essential Botanics - Valerian&Melissa formula prirodnog spokoja: ekstrakt valerijane, matičnjaka i origana umiruju nervni sistem, smanjuju razdražljivost",
    image: "/products/essential-botanics-valerian-i-melissa.png",
    price: 1250,
  },
  {
    slug: "essential-botanics-aronia-i-lutein",
    name: "Essential Botanics - Aronia&Lutein",
    brand: "Essential Botanics",
    categorySlugs: [
      "essential-botanics",
      "suplementi-za-vid",
      "duga-mladost",
    ],
    shortDescription:
      "Essential Botanics - Aronia&Lutein biljni kompleks na bazi antocijana luteina, borovnice i aronije pruža pouzdanu zaštitu očima od negativnih efekata",
    image: "/products/essential-botanics-aronia-i-lutein.png",
    price: 1050,
  },
  {
    slug: "essential-fatty-acids-omega-3-i-likopen",
    name: "Essential Fatty Acids - Omega-3 i likopen",
    brand: "Essential Fatty Acids",
    categorySlugs: ["essential-fatty-acids", "zdravo-srce", "anti-age-proizvode"],
    shortDescription:
      "Essential Fatty Acids - Omega-3 i likopen prirodni kardioprotektor za vašu svakodnevnu ishranu.",
    image: "/products/essential-fatty-acids-omega-3-i-likopen.png",
    price: 1600,
  },
  {
    slug: "beauty-box-lepota-i-sjaj",
    name: "BEAUTY BOX - Lepota i sjaj",
    brand: "Daily Box",
    categorySlugs: ["daily-box"],
    shortDescription:
      "BEAUTY BOX – Lepota i sjaj vitaminsko-antioksidativni kompleks obezbediće da vaša lepota i mladost ne zavise od okoline, stresa i nedostatka sna",
    image: "/products/beauty-box-lepota-i-sjaj.png",
    price: 2700,
  },
  {
    slug: "iq-box-intelekt",
    name: "IQ BOX - Intelekt",
    brand: "Daily Box",
    categorySlugs: ["daily-box", "suplementi-za-energiju-i-fokus"],
    shortDescription:
      "IQ BOX – Intelekt izbalansirani kompleks vitamina, biljnih ekstrakta i omega-3 masnih kiselina podstiče očuvanje visoke intelektualne aktivnosti",
    image: "/products/iq-box-intelekt.png",
    price: 2600,
  },
  {
    slug: "vision-box-ostar-vid",
    name: "VISION BOX - Oštar vid",
    brand: "Daily Box",
    categorySlugs: ["daily-box", "suplementi-za-vid"],
    shortDescription:
      "VISION Box – Oštar vid prirodni svetlosni filteri lutein i zeaksantin u kompleksu efikasno štite vizuelne ćelije, smanjujući opterećenje",
    image: "/products/vision-box-ostar-vid.png",
    price: 5300,
  },
  {
    slug: "siberian-super-natural-nutrition-stress-re-live",
    name: "Siberian Super Natural Nutrition - Stress Re.Live",
    brand: "Siberian Super Natural Nutrition",
    categorySlugs: ["siberian-super-natural-nutrition", "celicni-nervi"],
    shortDescription:
      "Siberian Super Natural Nutrition - Stress Re.Live inovativni organski kompleks za zaštitu nervnog sistema i prevenciju stresa",
    image: "/products/siberian-super-natural-nutrition-stress-re-live.png",
    price: 11500,
  },
  {
    slug: "fito-caj-od-divljeg-bilja-1-ciscenje-i-drenaza",
    name: "Fito čaj od divljeg bilja № 1 - Čišćenje i drenaža",
    brand: "Kolekcija fitočajeva",
    categorySlugs: ["kolekcija-fitocajeva", "detoks-i-ciscenje-organizma", "suplementi-za-decu"],
    shortDescription:
      "Fito čaj od divljeg bilja № 1 - Čišćenje i drenaža biljni čaj sa kurilskim čajem, senom i detelinom pružiće vam osećaj lakoće",
    image: "/products/fito-caj-od-divljeg-bilja-1-ciscenje-i-drenaza.png",
    price: 699,
  },
  {
    slug: "3d-flex-cube-sloboda-pokreta",
    name: "3D Flex Cube - Sloboda pokreta",
    brand: "3D Cube",
    categorySlugs: [
      "3d-cube",
      "elasticni-zglobovi",
      "duga-mladost",
      "cvrste-kosti",
    ],
    shortDescription:
      "3D Flex Cube - Sloboda pokreta maksimalna motorička aktivnost i lakoća kretanja - zahvaljujući kompleksnoj podršci hondroprotektora, omega-3 kiselina",
    image: "/products/3d-flex-cube-sloboda-pokreta.jpg",
    price: 9700,
  },
  {
    slug: "3d-hair-i-nails-cube-lepota-kose-i-noktiju",
    name: "3D Hair&Nails Cube - Lepota kose i noktiju",
    brand: "3D Cube",
    categorySlugs: ["3d-cube", "duga-mladost"],
    shortDescription:
      "3D Hair&Nails Cube - Lepota kose i noktiju maksimalno izbalansirani kompleks vitamina i minerala koji su neophodni za ishranu, rast",
    image: "/products/3d-hair-i-nails-cube-lepota-kose-i-noktiju.webp",
    price: 2800,
  },
  {
    slug: "3d-protection-cube",
    name: "3D Protection Cube",
    brand: "3D Cube",
    categorySlugs: [
      "3d-cube",
      "suplementi-za-energiju-i-fokus",
      "suplementi-za-imunitet",
    ],
    shortDescription: "3D Protection Cube premijalni kompleks deluje istovremeno u tri pravca:",
    image: "/products/3d-protection-cube.jpg",
    price: 4700,
  },
  {
    slug: "siberian-wellness-fito-caj-od-divljeg-bilja-4-lagani-dah",
    name: "Siberian Wellness Fito čaj od divljeg bilja № 4 - Lagani dah",
    brand: "Kolekcija fitočajeva",
    categorySlugs: ["kolekcija-fitocajeva", "suplementi-za-imunitet"],
    shortDescription:
      "Siberian Wellness Fito čaj od divljeg bilja № 4 - Lagani dah pri prvom znaku prehlade, pripremite šolju biljnog čaja sa kamilicom, lipom i majčinom dušicom",
    image: "/products/siberian-wellness-fito-caj-od-divljeg-bilja-4-lagani-dah.png",
    price: 699,
  },
  {
    slug: "3d-bone-vegan-cube-izdrzljivost-i-snaga",
    name: "3D Bone Vegan Cube - Izdržljivost i snaga",
    brand: "3D Cube",
    categorySlugs: [
      "3d-cube",
      "vegetarijanski-proizvodi",
      "cvrste-kosti",
      "anti-age-proizvode",
      "elasticni-zglobovi",
      "duga-mladost",
    ],
    shortDescription:
      "3D Bone Vegan Cube - Izdržljivost i snaga jedinstveni SMART- kompleks za snagu i jačanje koštanog sistema. Smanjuje rizik od oštećenja kostiju",
    image: "/products/3d-bone-vegan-cube-izdrzljivost-i-snaga.jpg",
    price: 7890,
  },
  {
    slug: "healthy-rhythms",
    name: "Healthy Rhythms",
    brand: "Healthy Rhythms",
    categorySlugs: [
      "healthy-rhythms",
      "anti-age-proizvode",
      "antistres-zastita",
      "suplementi-za-energiju-i-fokus",
      "elasticni-zglobovi",
      "zdravo-srce",
      "prevencija-dijabetesa",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Healthy Rhythms, kompletan vitaminsko-mineralni kompleks, usklađen sa hronobiološkim ritmovima tela, za održavanje zdravlja i radne sposobnosti.",
    image: "/products/healthy-rhythms.jpg",
    price: 2460,
  },
  {
    slug: "essential-fatty-acids-borage-and-amaranth-oil",
    name: "Essential Fatty Acids - Borage and Amaranth Oil",
    brand: "Essential Fatty Acids",
    categorySlugs: [
      "essential-fatty-acids",
      "prevencija-alergija",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Essential Fatty Acids - Borage and Amaranth Oil lipidni kompleks sadrži jednu od omega-6 kiselina - gamalinoleinskukiselinu i kompleks vitamina E i D.",
    image: "/products/essential-fatty-acids-borage-and-amaranth-oil.png",
    price: 2120,
  },
  {
    slug: "synchrovitals-vii-hronobioloska-zastita-vida",
    name: "Synchrovitals VII - Hronobiološka zaštita vida",
    brand: "Synchrovitals",
    categorySlugs: ["synchrovitals", "suplementi-za-vid"],
    shortDescription:
      "Synchrovitals VII - Hronobiološka zaštita vida je namenjen onima koji puno vremena provode ispred monitora kompjutera i drugih elektronskih uređaja",
    image: "/products/synchrovitals-vii-hronobioloska-zastita-vida.png",
    price: 4100,
  },
  {
    slug: "synchrovitals-vi-hronobioloska-zastita-zglobova",
    name: "Synchrovitals VI - Hronobiološka zaštita zglobova",
    brand: "Synchrovitals",
    categorySlugs: [
      "synchrovitals",
      "elasticni-zglobovi",
      "cvrste-kosti",
    ],
    shortDescription:
      "Synchrovitals VI - Hronobiološka zaštita zglobova predstavlja obnovljen kompleks za normalizovanje i zaštitu stanja vezivnog tkiva",
    image: "/products/synchrovitals-vi-hronobioloska-zastita-zglobova.png",
    price: 2850,
  },
  {
    slug: "synchrovitals-ii-hronobioloska-zastita-mozga",
    name: "Synchrovitals II - Hronobiološka zaštita mozga",
    brand: "Synchrovitals",
    categorySlugs: [
      "synchrovitals",
      "suplementi-za-energiju-i-fokus",
      "duga-mladost",
    ],
    shortDescription:
      "Synchrovitals II - Hronobiološka zaštita mozga dvofazni neurozaštitni kompleks na bazi ekstrakata ginko bilobe, žen-šena, gotu kole i bajkalske kapice",
    image: "/products/synchrovitals-ii-hronobioloska-zastita-mozga.png",
    price: 3600,
  },
  {
    slug: "komplet-za-kompleksno-ciscenje-organizma",
    name: "Komplet za kompleksno čišćenje organizma",
    brand: "Renaissance Triple Set",
    categorySlugs: [
      "renaissance-triple-set",
      "detoks-i-ciscenje-organizma",
      "suplementi-za-energiju-i-fokus",
      "elasticni-zglobovi",
      "duga-mladost",
      "suplementi-za-zeludac-i-creva",
      "suplementi-za-jetru",
      "zdravi-bubrezi",
      "zdravo-srce",
      "suplementi-za-vid",
      "prevencija-alergija",
      "prevencija-dijabetesa",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Komplet za kompleksno čišćenje organizma  predstavlja principijelno nov sistem kompleksnog čišćenja organizma na ćelijskom nivou",
    image: "/products/komplet-za-kompleksno-ciscenje-organizma.png",
    price: 3500,
  },
  {
    slug: "trigelm-paracleanse-triple-set",
    name: "Trigelm - Paracleanse Triple Set",
    brand: "Paracleanse Triple Set",
    categorySlugs: [
      "paracleanse-triple-set",
      "suplementi-za-zeludac-i-creva",
      "suplementi-za-jetru",
    ],
    shortDescription:
      "Trigelm - Paracleanse Triple Set trofazni biljni kompleks za normalizovanje funkcije creva i održavanje mikroflore.",
    image: "/products/trigelm-paracleanse-triple-set.png",
    price: 3100,
  },
  {
    slug: "synchrovitals-v-hronobioloska-zastita-imuniteta",
    name: "Synchrovitals V - Hronobiološka zaštita imuniteta",
    brand: "Synchrovitals",
    categorySlugs: [
      "synchrovitals",
      "suplementi-za-imunitet",
      "suplementi-za-energiju-i-fokus",
      "prevencija-alergija",
    ],
    shortDescription:
      "Synchrovitals V - Hronobiološka zaštita imuniteta se preporučuje odraslima kao izvor ginsenozida i dodatni izvor apigenina.",
    image: "/products/synchrovitals-v-hronobioloska-zastita-imuniteta.png",
    price: 2150,
  },
  {
    slug: "adaptovit",
    name: "Adaptovit",
    brand: "Adaptovit",
    categorySlugs: [
      "adaptovit",
      "suplementi-za-energiju-i-fokus",
      "suplementi-za-imunitet",
    ],
    shortDescription: "„Adaptovit“ energomodulirajući kompleks  u spreju.",
    image: "/products/adaptovit.jpg",
    price: 1250,
  },
  {
    slug: "chronolong-women-s-health",
    name: "Chronolong - Women's Health",
    brand: "Women's Health",
    categorySlugs: ["womens-health", "suplementi-za-energiju-i-fokus"],
    shortDescription:
      "Chronolong – Women's Health je prirodni dodatak ishrani sa fitoestrogenima za hormonski balans, lepotu i vitalnost žena 35+.",
    image: "/products/chronolong-women-s-health.jpg",
    price: 3400,
  },
  {
    slug: "trimegavitals-all-natural-beta-carotene-i-sea-buckthorn-oil",
    name: "Trimegavitals - All-Natural Beta-Carotene&Sea Buckthorn Oil",
    brand: "Essential Fatty Acids",
    categorySlugs: [
      "essential-fatty-acids",
      "duga-mladost",
      "suplementi-za-zeludac-i-creva",
      "zdravo-srce",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Trimegavitals - All-Natural Beta-Carotene&Sea Buckthorn Oil formula sa prirodnim beta-karotenom smanjuje negativne efekte UV zračenja",
    image: "/products/trimegavitals-all-natural-beta-carotene-i-sea-buckthorn-oil.png",
    price: 1250,
  },
  {
    slug: "fito-caj-od-divljeg-bilja-2-zenska-harmonija",
    name: "Fito čaj od divljeg bilja № 2 - Ženska harmonija",
    brand: "Kolekcija fitočajeva",
    categorySlugs: ["kolekcija-fitocajeva", "suplementi-za-zene"],
    shortDescription:
      "Fito čaj od divljeg bilja № 2 - Ženska harmonija mirisna mešavina na bazi žalfije, matičnjaka, nane i klevera će vas ispuniti spokojem",
    image: "/products/fito-caj-od-divljeg-bilja-2-zenska-harmonija.png",
    price: 699,
  },
  {
    slug: "siberian-wellness-fito-caj-od-divljeg-bilja-3-prirodni-antistres",
    name: "Siberian Wellness Fito čaj od divljeg bilja № 3 - Prirodni antistres",
    brand: "Kolekcija fitočajeva",
    categorySlugs: ["kolekcija-fitocajeva", "antistres-zastita"],
    shortDescription:
      "Siberian Wellness Fito čaj od divljeg bilja № 3 - Prirodni antistres šolja mirisnog čaja prijatnog biljnog ukusa pomoći će vam da se opustite",
    image: "/products/siberian-wellness-fito-caj-od-divljeg-bilja-3-prirodni-antistres.png",
    price: 699,
  },
  {
    slug: "fito-caj-od-divljeg-bilja-5-komforno-varenje",
    name: "Fito čaj od divljeg bilja № 5 - Komforno varenje",
    brand: "Kolekcija fitočajeva",
    categorySlugs: [
      "kolekcija-fitocajeva",
      "suplementi-za-zeludac-i-creva",
      "detoks-i-ciscenje-organizma",
    ],
    shortDescription:
      "Fito čaj od divljeg bilja № 5 - Komforno varenje osetite komfor i lakoću zahvaljujući jedinstvenom sastavu sibirskog bilja u čaju iz Siberian Wellnessa!",
    image: "/products/fito-caj-od-divljeg-bilja-5-komforno-varenje.png",
    price: 699,
  },
  {
    slug: "fito-caj-od-divljeg-bilja-6-zastita-jetre",
    name: "Fito čaj od divljeg bilja № 6 - Zaštita jetre",
    brand: "Kolekcija fitočajeva",
    categorySlugs: [
      "kolekcija-fitocajeva",
      "suplementi-za-jetru",
      "suplementi-za-zeludac-i-creva",
    ],
    shortDescription:
      "Fito čaj od divljeg bilja № 6 - Zaštita jetre osvežavajući biljni čaj blagotvorno deluje na funkciju jetre, podstiče brzi oporavak ćelija",
    image: "/products/fito-caj-od-divljeg-bilja-6-zastita-jetre.png",
    price: 699,
  },
  {
    slug: "fito-caj-od-divljeg-bilja-7-lakoca-pokreta",
    name: "Fito čaj od divljeg bilja № 7 - Lakoća pokreta",
    brand: "Kolekcija fitočajeva",
    categorySlugs: ["kolekcija-fitocajeva", "elasticni-zglobovi"],
    shortDescription:
      "Fito čaj od divljeg bilja № 7 - Lakoća pokreta prirodna podrška zglobovima - u svakoj šolji mirisnog napitka!",
    image: "/products/fito-caj-od-divljeg-bilja-7-lakoca-pokreta.png",
    price: 699,
  },
  {
    slug: "fito-caj-od-divljeg-bilja-8-komfor-za-srce",
    name: "Fito čaj od divljeg bilja № 8 - Komfor za srce",
    brand: "Kolekcija fitočajeva",
    categorySlugs: ["kolekcija-fitocajeva", "zdravo-srce"],
    shortDescription:
      "Fito čaj od divljeg bilja № 8 - Komfor za srce podržite srce pomoću sibirskog bilja i uživajte u ukusu prirodnog čaja.",
    image: "/products/fito-caj-od-divljeg-bilja-8-komfor-za-srce.png",
    price: 699,
  },
  {
    slug: "fito-caj-od-divljeg-bilja-9-kontrola-ugljenih-hidrata",
    name: "Fito čaj od divljeg bilja № 9 - Kontrola ugljenih hidrata",
    brand: "Kolekcija fitočajeva",
    categorySlugs: ["kolekcija-fitocajeva", "prevencija-dijabetesa"],
    shortDescription:
      "Fito čaj od divljeg bilja № 9 - Kontrola ugljenih hidrata šolja aromatičnog biljnog čaja na bazi korena čička, trave lucerke i izdanaka borovnice",
    image: "/products/fito-caj-od-divljeg-bilja-9-kontrola-ugljenih-hidrata.png",
    price: 699,
  },
  {
    slug: "bcaa-complex-fitness-catalist",
    name: "BCAA Complex - Fitness Catalist",
    brand: "Fitness Catalyst",
    categorySlugs: ["fitness-catalyst"],
    shortDescription:
      "BCAA Complex - Fitness Catalist za intenzivne treninge, sadrži tri vrste aminokiselina u idealnom odnosu za anabolizam: L-valin, L-izoleucin i L-leucin.",
    image: "/products/bcaa-complex-fitness-catalist.png",
    price: 2900,
  },
  {
    slug: "essential-vitamins-vitamin-d3",
    name: "Essential Vitamins - Vitamin D3",
    brand: "Essential Vitamins",
    categorySlugs: [
      "essential-vitamins",
      "anti-age-proizvode",
      "suplementi-za-energiju-i-fokus",
      "elasticni-zglobovi",
      "cvrste-kosti",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Essential Vitamins - Vitamin D3, rastvor za oralnu upotrebu je dijetetski suplement sa vitaminom D.",
    image: "/products/essential-vitamins-vitamin-d3.png",
    price: 1250,
  },
  {
    slug: "sirup-za-imunitet-immunotops-vitamama",
    name: "Sirup za imunitet Immunotops - Vitamama",
    brand: "Vitamama",
    categorySlugs: ["vitamama", "suplementi-za-imunitet"],
    shortDescription:
      "Sirup za imunitet Immunotops - Vitamama ukusni prirodni pomoćnik imunog sistema! Bez šećera, ali sa inulinskim sirupom za crevni mikrobiom",
    image: "/products/sirup-za-imunitet-immunotops-vitamama.png",
    price: 990,
  },
  {
    slug: "essential-vitamins-natural-vitamin-e",
    name: "Essential Vitamins - Natural Vitamin E",
    brand: "Essential Vitamins",
    categorySlugs: [
      "essential-vitamins",
      "anti-age-proizvode",
      "zdravo-srce",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Essential Vitamins - Natural Vitamin E  prirodni izvor vitamina E iz semenki suncokreta u visoko prečišćenom MCT ulju.",
    image: "/products/essential-vitamins-natural-vitamin-e.png",
    price: 1500,
  },
  {
    slug: "relax-box-zastita-od-stresa",
    name: "RELAX BOX - Zaštita od stresa",
    brand: "Daily Box",
    categorySlugs: ["daily-box", "antistres-zastita"],
    shortDescription:
      "RELAX BOX – Zaštita od stresa s organskim magnezijumom i biljnim ekstraktima za maksimalnu kontrolu stresa i harmonizovanje emocionalnog stanja.",
    image: "/products/relax-box-zastita-od-stresa.jpg",
    price: 4500,
  },
  {
    slug: "gluco-box-kontrola-ugljenih-hidrata",
    name: "GLUCO BOX - Kontrola ugljenih hidrata",
    brand: "Daily Box",
    categorySlugs: ["daily-box"],
    shortDescription:
      "GLUCO BOX - Kontrola ugljenih hidrata izbalansiran kompleks za kontrolu nivoa šećera i borbu protiv metaboličkog sindroma.",
    image: "/products/gluco-box-kontrola-ugljenih-hidrata.jpg",
    price: 5900,
  },
  {
    slug: "immuno-box-zastita-od-infekcija",
    name: "IMMUNO BOX - Zaštita od infekcija",
    brand: "Daily Box",
    categorySlugs: ["daily-box", "suplementi-za-imunitet", "suplementi-za-energiju-i-fokus"],
    shortDescription:
      "IMMUNO BOX - Zaštita od infekcija kompleksna zaštita tela: prirodni imunostimulansi, biljni antiseptici i prirodni adaptogeni - za odlično zdravlje",
    image: "/products/immuno-box-zastita-od-infekcija.jpg",
    price: 3100,
  },
  {
    slug: "lite-step-box-lagani-hod",
    name: "LITE STEP BOX - Lagani hod",
    brand: "Daily Box",
    categorySlugs: [
      "daily-box",
      "anti-age-proizvode",
      "duga-mladost",
      "cvrste-kosti",
    ],
    shortDescription:
      "LITE STEP BOX - Lagani hod dvostepena zaštita od proširenih vena: normalizuje cirkulaciju krvi, jača zidove kapilara i krvnih sudova.",
    image: "/products/lite-step-box-lagani-hod.jpg",
    price: 4900,
  },
  {
    slug: "essential-vitamins-diosmin-i-rutin",
    name: "Essential Vitamins - Diosmin i rutin",
    brand: "Essential Vitamins",
    categorySlugs: [
      "essential-vitamins",
      "anti-age-proizvode",
      "duga-mladost",
      "zdravo-srce",
    ],
    shortDescription:
      "Essential Vitamins - Diosmin i rutin prirodni venotonik na bazi diosmina i rutina za sprečavanje narušavanja limfotoka i cirkulacije u nogama.",
    image: "/products/essential-vitamins-diosmin-i-rutin.png",
    price: 3700,
  },
  {
    slug: "corenrg-urban-immunobooster",
    name: "CoreNRG Urban Immunobooster",
    brand: "CoreNRG",
    categorySlugs: [
      "corenrg",
      "suplementi-za-energiju-i-fokus",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "CoreNRG Urban Immunobooster moćan koncentrat soka od jele, pojačan ekstraktima sibirskih adaptogenih biljaka. Svaka kap sadrži snagu cele Sibirske tajge!",
    image: "/products/corenrg-urban-immunobooster.webp",
    price: 1700,
  },
  {
    slug: "essential-minerals-zinc-with-siberian-herbs",
    name: "Essential Minerals - Zinc with Siberian herbs",
    brand: "Essential Minerals Elemvitals",
    categorySlugs: [
      "essential-minerals-elemvitals",
      "anti-age-proizvode",
      "suplementi-za-energiju-i-fokus",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Essential Minerals - Zinc with Siberian herbs kompleks sa organskim cinkom i bakrom u kombinaciji sa biljnim ekstraktima štiti telo od slobodnih radikala",
    image: "/products/essential-minerals-zinc-with-siberian-herbs.png",
    price: 1800,
  },
  {
    slug: "essential-mineral-magnesium-with-siberian-herbs",
    name: "Essential Mineral - Magnesium with Siberian herbs",
    brand: "Essential Minerals Elemvitals",
    categorySlugs: [
      "essential-minerals-elemvitals",
      "antistres-zastita",
      "suplementi-za-energiju-i-fokus",
      "duga-mladost",
      "zdravo-srce",
      "cvrste-kosti",
    ],
    shortDescription:
      "Essential Mineral - Magnesium with Siberian herbs kompleks sa glavnim mineralom relaksiranja - organskim magnezijumom, obogaćenim ekstraktom valerijane",
    image: "/products/essential-mineral-magnesium-with-siberian-herbs.png",
    price: 1600,
  },
  {
    slug: "elbifid-essential-probiotics",
    name: "Elbifid - Essential Probiotics",
    brand: "Essential Probiotics",
    categorySlugs: [
      "essential-probiotics",
      "suplementi-za-zeludac-i-creva",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Elbifid - Essential Probiotics dodatak ishrani s lakto i bifidobakterijama.Probiotički kompleks koji je po sastavu blizak prirodnom crevnom mikrobiomu.",
    image: "/products/elbifid-essential-probiotics.png",
    price: 1900,
  },
  {
    slug: "eljbesen-novo-pakovanje",
    name: "Eljbešen novo pakovanje",
    brand: "Sibirski balzami",
    categorySlugs: ["sibirski-balzami"],
    shortDescription:
      "Eljbešen novo pakovanje floraseptični balzam na bazi eteričnih ulja i ekstrakta makleije štiti usnu šupljinu i kožu od bakterija i ima dezodorirajući efekat.",
    image: "/products/eljbesen-novo-pakovanje.png",
    price: 950,
  },
  {
    slug: "tonizirajuca-krema-za-noge-sibirski-balzam",
    name: "Tonizirajuća krema za noge - Sibirski balzam",
    brand: "Sibirski balzami",
    categorySlugs: ["sibirski-balzami"],
    shortDescription:
      "Tonirajuća krema za besprekorne noge sa aktivnim tonirajućim kompleksom za brzo otklanjanje umora i osećaja težine u nogama.",
    image: "/products/tonizirajuca-krema-za-noge-sibirski-balzam.png",
    price: 1740,
  },
  {
    slug: "obnavljajuci-balzam-za-kozu-siberian-wellnes",
    name: "Obnavljajući balzam za kožu - Siberian Wellnes",
    brand: "Sibirski balzami",
    categorySlugs: ["sibirski-balzami"],
    shortDescription:
      'Obnavljajući balzam za kožu u potpunosti prirodni balzam sa smolom - univerzalni "spasilac" za celu porodicu!',
    image: "/products/obnavljajuci-balzam-za-kozu-siberian-wellnes.png",
    price: 890,
  },
  {
    slug: "calcitops-hrskave-kuglice-s-kakao-uljem-malina-vitamama",
    name: "Calcitops, hrskave kuglice s kakao uljem malina - Vitamama",
    brand: "Vitamama",
    categorySlugs: ["vitamama"],
    shortDescription:
      "Calcitops, hrskave kuglice s kakao uljem malina - Vitamama pokloniće snagu i postaće izvor kalcijuma za harmoničan rast.",
    image: "/products/calcitops-hrskave-kuglice-s-kakao-uljem-malina-vitamama.png",
    price: 1150,
  },
  {
    slug: "protein-surutke-fitness-catalyst-sladoled-od-vanile",
    name: "Protein surutke Fitness Catalyst - sladoled od vanile",
    brand: "Proteini",
    categorySlugs: ["proteini"],
    shortDescription:
      "Protein surutke Fitness Catalyst - sladoled od vanile Izuzetno kvalitetan koncentrat proteina surutke s izuzetnim ukusom i odličnim aminokiselinama.",
    image: "/products/protein-surutke-fitness-catalyst-sladoled-od-vanile.png",
    price: 4200,
  },
  {
    slug: "protein-surutke-fitness-catalyst-cokoladni-keks",
    name: "Protein surutke Fitness Catalyst - čokoladni keks",
    brand: "Proteini",
    categorySlugs: ["proteini"],
    shortDescription:
      "Protein surutke Fitness Catalyst - čokoladni keks Izuzetno kvalitetan koncentrat proteina surutke s izuzetnim ukusom i odličnim aminokiselinama.",
    image: "/products/protein-surutke-fitness-catalyst-cokoladni-keks.png",
    price: 4200,
  },
  {
    slug: "sportski-obnavljajuci-gel-fitness-catalist",
    name: "Sportski obnavljajući gel - Fitness Catalist",
    brand: "Fitness Catalyst",
    categorySlugs: ["fitness-catalyst", "elasticni-zglobovi"],
    shortDescription:
      "Sportski obnavljajući gel - Fitness Catalist otklanja neprijatan osećaj da ste se preforsirali i ubrzava obnavljanje nakon intenzivnog fizičkog opterećenja.",
    image: "/products/sportski-obnavljajuci-gel-fitness-catalist.png",
    price: 1900,
  },
  {
    slug: "siberian-super-natural-sport-l-carnitine-fitness-catalist",
    name: "Siberian Super Natural Sport L-Carnitine - Fitness Catalist",
    brand: "Fitness Catalyst",
    categorySlugs: ["fitness-catalyst"],
    shortDescription:
      "Siberian Super Natural Sport L-Carnitine - Fitness Catalist učestvuje u razmeni masti, povećava izdržljivost organizma prilikom bavljenja aerobnim vrstama sporta",
    image: "/products/siberian-super-natural-sport-l-carnitine-fitness-catalist.png",
    price: 3700,
  },
  {
    slug: "omega-3-ultra-fitness-catalist",
    name: "Omega-3 Ultra - Fitness Catalist",
    brand: "Fitness Catalyst",
    categorySlugs: [
      "fitness-catalyst",
      "cvrste-kosti",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Maksimum Omega-3 Ultra - Fitness Catalist kiselina za snažnu podršku telu tokom intenzivne fizičke aktivnosti.",
    image: "/products/omega-3-ultra-fitness-catalist.png",
    price: 5200,
  },
  {
    slug: "chromlipaza-fitness-catalist",
    name: "Chromlipaza - Fitness Catalist",
    brand: "Fitness Catalyst",
    categorySlugs: [
      "fitness-catalyst",
      "anti-age-proizvode",
      "prevencija-dijabetesa",
    ],
    shortDescription:
      "Chromlipaza - Fitness Catalist je idealan suplement za sve koji žele efikasno da kontrolišu svoju težinu i apetit.",
    image: "/products/chromlipaza-fitness-catalist.png",
    price: 2200,
  },
  {
    slug: "metilsulfonilmetan-fitness-catalyst",
    name: "Metilsulfonilmetan - Fitness Catalyst",
    brand: "Fitness Catalyst",
    categorySlugs: ["fitness-catalyst", "elasticni-zglobovi"],
    shortDescription:
      "Metilsulfonilmetan - Fitness Catalyst je jedinjenje organskog sumpora, koje je odgovorno za sintezu hrskavice i vezivnog tkiva",
    image: "/products/metilsulfonilmetan-fitness-catalyst.png",
    price: 1900,
  },
  {
    slug: "essential-sorbents-prirodni-inulinski-koncentrat",
    name: "Essential Sorbents Prirodni inulinski koncentrat",
    brand: "Essential Sorbents",
    categorySlugs: [
      "essential-sorbents-lymphosan",
      "suplementi-za-zeludac-i-creva",
      "prevencija-dijabetesa",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Essential Sorbents Prirodni inulinski koncentrat- kompleks biološki aktivnih supstanci izuzetno je delotvoran",
    image: "/products/essential-sorbents-prirodni-inulinski-koncentrat.png",
    price: 930,
  },
  {
    slug: "mama-box-dojenje",
    name: "MAMA BOX - Dojenje",
    brand: "Daily Box",
    categorySlugs: ["daily-box", "suplementi-za-trudnice-i-dojilje", "suplementi-za-decu"],
    shortDescription:
      "MAMA BOX_- Dojenje, vitamini, minerali i dragocene omega-3 za dojilju i bebu.",
    image: "/products/mama-box-dojenje.jpg",
    price: 4950,
  },
  {
    slug: "omegalodon-multifruit-kompleks-omega-3-kiselina-vitamama",
    name: "OMEGAlodon multifruit, kompleks omega-3 kiselina - Vitamama",
    brand: "Vitamama",
    categorySlugs: ["vitamama"],
    shortDescription:
      "OMEGAlodon multifruit, kompleks omega-3 kiselina - Vitamama,  s vitaminima A, D3, E i voćnim mirisom će se pobrinuti o zdravlju vaše dece",
    image: "/products/omegalodon-multifruit-kompleks-omega-3-kiselina-vitamama.png",
    price: 1600,
  },
  {
    slug: "l-arginin-fitness-catalyst",
    name: "L-arginin - Fitness Catalyst",
    brand: "Fitness Catalyst",
    categorySlugs: ["fitness-catalyst"],
    shortDescription:
      "L-arginin – Fitness Catalyst izvor aminokiselina za jačanje i povećavanje mišićne mase tokom treninga i ubrzani oporavak mišića nakon vežbanja.",
    image: "/products/l-arginin-fitness-catalyst.png",
    price: 3250,
  },
  {
    slug: "instant-veganski-bcaa-kompleks-guarana-fitness-catalist",
    name: "Instant veganski BCAA  kompleks - Guarana - Fitness Catalist",
    brand: "Fitness Catalyst",
    categorySlugs: ["fitness-catalyst", "vegetarijanski-proizvodi"],
    shortDescription:
      "Instant veganski BCAA kompleks - Guarana - Fitness Catalist napitak s aminokiselinama i guaranom je stvoren za one koji su uvek u pokretu",
    image: "/products/instant-veganski-bcaa-kompleks-guarana-fitness-catalist.png",
    price: 1250,
  },
  {
    slug: "greenpin-omeksivac-za-ves-za-sve-tipove-tkanina",
    name: "GreenPin Omekšivač za veš za sve tipove tkanina",
    brand: "GreenPin",
    categorySlugs: ["greenpin"],
    shortDescription:
      "GreenPin Omekšivač za veš za sve tipove tkanina sa maksimalno nežnim komponentama – prava briga o stvarima.",
    image: "/products/greenpin-omeksivac-za-ves-za-sve-tipove-tkanina.png",
    price: 1400,
  },
  {
    slug: "greenpin-bathroom-cleaner",
    name: "GreenPin Bathroom Cleaner",
    brand: "GreenPin",
    categorySlugs: ["greenpin"],
    shortDescription:
      "GreenPin Bathroom Cleaner je pogodno za čišćenje keramičkih pločica, keramičkih sudopera i sudopera od nerđajućeg čelika, tuš kabina i toaleta.",
    image: "/products/greenpin-bathroom-cleaner.png",
    price: 700,
  },
  {
    slug: "greenpin-dish-soap",
    name: "GreenPin Dish soap",
    brand: "GreenPin",
    categorySlugs: ["greenpin"],
    shortDescription:
      "GreenPin Dish soap univerzalno ekosredstvo za pranje sudova, voća i povrća. Lako se ispira i brine o koži ruku.",
    image: "/products/greenpin-dish-soap.png",
    price: 880,
  },
  {
    slug: "greenpin-multi-purpose-cleaner",
    name: "GreenPin Multi-Purpose Cleaner",
    brand: "GreenPin",
    categorySlugs: ["greenpin"],
    shortDescription:
      "GreenPin Multi-Purpose Cleaner univerzalno sredstvo za čišćenje pogodno je za uklanjanje zaprljanih površina (zidova, pločica, nameštaja i podova).",
    image: "/products/greenpin-multi-purpose-cleaner.png",
    price: 1270,
  },
  {
    slug: "turbo-caj-caj-za-ciscenje",
    name: "Turbo čaj - čaj za čišćenje",
    brand: "Renaissance Triple Set",
    categorySlugs: [
      "renaissance-triple-set",
      "detoks-i-ciscenje-organizma",
      "suplementi-za-zeludac-i-creva",
    ],
    shortDescription:
      "Turbo čaj – čaj za čišćenje je fitodetoks za vaše telo: sena poboljšava varenje, pomaže u uklanjanju viška tečnosti, daje lakoću i komfor, đumbir",
    image: "/products/turbo-caj-caj-za-ciscenje.png",
    price: 750,
  },
  {
    slug: "krema-za-lice-hidratantna-siberian-wellness",
    name: "Krema za lice hidratantna - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Krema za lice hidratantna Siberian Wellness bioaktivna lagana krema sa kompleksom ekstrakata sibirskih endema vlaži kožu, ispunjava je vitalnošću i mladošću",
    image: "/products/krema-za-lice-hidratantna-siberian-wellness.png",
    price: 1550,
  },
  {
    slug: "pasta-za-zube-sa-sibirskim-propolisom",
    name: "Pasta za zube sa Sibirskim propolisom",
    brand: "Paste za zube",
    categorySlugs: ["paste-za-zube"],
    shortDescription: "Pasta za zube sa Sibirskim propolisom 98,7% sastojaka prirodnog porekla.",
    image: "/products/pasta-za-zube-sa-sibirskim-propolisom.png",
    price: 750,
  },
  {
    slug: "anticelulit-koncentrat-experalta-platinum",
    name: "Anticelulit koncentrat - Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Anticelulit koncentrat - Experalta Platinum inovacija kompleks Brown Slim smanjuje obim struka i efekat „pomorandžine kore“ na bokovima",
    image: "/products/anticelulit-koncentrat-experalta-platinum.png",
    price: 3000,
  },
  {
    slug: "pasta-za-zube-sa-morskim-kalcijumom",
    name: "Pasta za zube sa morskim kalcijumom",
    brand: "Paste za zube",
    categorySlugs: ["paste-za-zube"],
    shortDescription:
      "Pasta za zube sa morskim kalcijumom remineralizujuća pasta sa dve vrste kalcijuma – organskog kalcijuma kao dela multimineralnog kompleksa",
    image: "/products/pasta-za-zube-sa-morskim-kalcijumom.png",
    price: 750,
  },
  {
    slug: "blagi-gel-za-umivanje-s-probiotikom-experalta-platinum",
    name: "Blagi gel za umivanje s probiotikom - Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Blagi gel za umivanje s probiotikom - Experalta Platinum nežan gel za čišćenje sa kompleksom pre- i probiotika pažljivo uklanja tragove prljavštine",
    image: "/products/blagi-gel-za-umivanje-s-probiotikom-experalta-platinum.png",
    price: 1800,
  },
  {
    slug: "koncentrat-u-ampuli-lifting-i-elasticnost-experalta-platinum",
    name: "Koncentrat u ampuli lifting i elastičnost - Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Koncentrat u ampuli lifting i elastičnost – Experalta Platinum deluje u tri pravca odjednom: podstiču smanjenje sitnih i dubokih bora",
    image: "/products/koncentrat-u-ampuli-lifting-i-elasticnost-experalta-platinum.png",
    price: 2500,
  },
  {
    slug: "koncentrat-u-ampuli-sa-bakuciolom-experalta-platinum",
    name: "Koncentrat u ampuli sa bakučiolom - Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Koncentrat u ampuli sa bakučiolom– Experalta Platinum biljnim analogom retinola koji poboljšava kvalitet kože.",
    image: "/products/koncentrat-u-ampuli-sa-bakuciolom-experalta-platinum.png",
    price: 2400,
  },
  {
    slug: "pipeta-za-serum-experalta-platinum",
    name: "Pipeta za serum - Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Kupujući kozmetičku pipetu za serum – Experalta Platinum, koja se može koristiti više puta, vi dajete realni doprinos brizi o budućnosti naše planete.",
    image: "/products/pipeta-za-serum-experalta-platinum.png",
    price: 130,
  },
  {
    slug: "raskosna-obnavljajuca-micelarna-voda-za-lice-experalta-platinum",
    name: "Raskošna obnavljajuća micelarna voda za lice - Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Raskošna obnavljajuća micelarna voda za lice - Experalta Platinum na biljnoj bazi fino skida šminku i čisti s kože prljavštinu",
    image: "/products/raskosna-obnavljajuca-micelarna-voda-za-lice-experalta-platinum.png",
    price: 1950,
  },
  {
    slug: "hidrofilno-ulje-za-ciscenje-experalta-platinum",
    name: "Hidrofilno ulje za čišćenje - Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Hidrofilno ulje za čišćenje - Experalta Platinum kože sa prirodnim uljima i vitaminom E.",
    image: "/products/hidrofilno-ulje-za-ciscenje-experalta-platinum.png",
    price: 1950,
  },
  {
    slug: "krema-za-povecanje-elasticnosti-koze-oko-ociju-experalta-platinum",
    name: "Krema za povećanje elastičnosti kože oko očiju - Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Krema za povećanje elastičnosti kože oko očiju – Experalta Platinum moćna anti-age formula na bazi biljnih peptida kedrovih oraha i sibirskog ženšena",
    image: "/products/krema-za-povecanje-elasticnosti-koze-oko-ociju-experalta-platinum.png",
    price: 1700,
  },
  {
    slug: "pametna-krema-za-lice-sa-biljnim-peptidima-experalta-platinum",
    name: "Pametna krema za lice sa biljnim peptidima - Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Pametna krema za lice sa biljnim peptidima – Experalta Platinum pametni sistem za mladost kože sa biljnim peptidima i energetskim kompleksom HerbaGlow",
    image: "/products/pametna-krema-za-lice-sa-biljnim-peptidima-experalta-platinum.png",
    price: 5200,
  },
  {
    slug: "pametni-serum-za-lice-sa-biljnim-peptidima-experalta-platinum",
    name: "Pametni serum za lice sa biljnim peptidima - Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Pametni serum za lice sa biljnim peptidima – Experalta Platinum inovativna formula aktivno deluje u dubokim slojevima kože",
    image: "/products/pametni-serum-za-lice-sa-biljnim-peptidima-experalta-platinum.png",
    price: 4990,
  },
  {
    slug: "dezodorans-za-telo-siberian-wellness",
    name: "Dezodorans za telo - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Dezodorans za telo – Siberian Wellness sa kalijum alumom efikasno reguliše prekomerno znojenje. Zahvaljujući prirodnim sastojcima, proizvod ne začepljuje pore",
    image: "/products/dezodorans-za-telo-siberian-wellness.png",
    price: 970,
  },
  {
    slug: "maska-za-izbeljivanje-siberian-wellness",
    name: "Maska za izbeljivanje - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Maska za izbeljivanje – Siberian Wellness sa niacinamidom i alfa-arbutinom sprečava višak proizvodnje melanina, podstiče efekat posvetljavanja",
    image: "/products/maska-za-izbeljivanje-siberian-wellness.png",
    price: 1100,
  },
  {
    slug: "sampon-za-suvu-i-farbanu-kosu-siberian-wellness",
    name: "Šampon za suvu i farbanu kosu - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Hranljivi Šampon za suvu i farbanu kosu – Siberian Wellness sa ceramidama i proteinima pšenice fino čisti i obnavlja oštećenu i farbanu kosu",
    image: "/products/sampon-za-suvu-i-farbanu-kosu-siberian-wellness.png",
    price: 1200,
  },
  {
    slug: "hidratantni-sampon-siberian-wellness",
    name: "Hidratantni šampon - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Hidratantni šampon – Siberian Wellness efikasno i brižljivo pere kosu i kožu glave, pogodan je za svakodnevno korišćenje.",
    image: "/products/hidratantni-sampon-siberian-wellness.png",
    price: 1200,
  },
  {
    slug: "hidratantna-krema-za-ruke-sa-ekstraktom-semena-grozdja-siberian-wellness",
    name: "Hidratantna krema za ruke sa ekstraktom semena grožđa - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Hidratantna krema za ruke sa ekstraktom semena grožđa – Siberian Wellness, tonus i elastičnost sigurni su znaci lepe i mladalačke kože ruku",
    image: "/products/hidratantna-krema-za-ruke-sa-ekstraktom-semena-grozdja-siberian-wellness.png",
    price: 750,
  },
  {
    slug: "balzam-za-telo-spongilla-i-gavez-zivokost-siberian-wellness",
    name: "Balzam za telo Spongilla&Gavez Živokost - Siberian Wellness",
    brand: "Sibirski balzami",
    categorySlugs: ["sibirski-balzami", "elasticni-zglobovi"],
    shortDescription:
      "Balzam za telo Spongilla&Gavez Živokost – Siberian Wellness prirodni balzam sa biljnim ekstraktima pomaže u vraćanju osećaja lakoće",
    image: "/products/balzam-za-telo-spongilla-i-gavez-zivokost-siberian-wellness.png",
    price: 900,
  },
  {
    slug: "sampon-za-ostecenu-kosu-siberian-wellness",
    name: "Šampon za oštećenu kosu - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Šampon za oštećenu kosu – Siberian Wellness sa ekstraktom čilija i niacinamidom efikasno čisti i podstiče normalizovanje folikula vlasi",
    image: "/products/sampon-za-ostecenu-kosu-siberian-wellness.png",
    price: 1500,
  },
  {
    slug: "sampon-za-volumen-kose-siberian-wellness",
    name: "Šampon za volumen kose - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Šampon za volumen kose – Siberian Wellness sa fitokeratinom i sukcinskom kiselinom blago čisti kožu i kosu, podstiče smanjenje mašćenja.",
    image: "/products/sampon-za-volumen-kose-siberian-wellness.png",
    price: 1200,
  },
  {
    slug: "hidratantna-pena-za-ciscenje-lica-siberian-wellness-herbal-cosmetics",
    name: "Hidratantna pena za čišćenje lica - Siberian Wellness Herbal Cosmetics",
    brand: "Kozmetika Siberian Wellness Herbal Cosmetics",
    categorySlugs: ["kozmetika-siberian-wellness-herbal-cosmetics"],
    shortDescription:
      "Hidratantna pena za čišćenje lica – Siberian Wellness Herbal Cosmetics lagana, nežna pena sa sokom aloe vere i mlečnom kiselinom nežno čisti, umiruje i hidrira",
    image: "/products/hidratantna-pena-za-ciscenje-lica-siberian-wellness-herbal-cosmetics.png",
    price: 1100,
  },
  {
    slug: "pena-za-intimnu-higijenu-siberian-wellness-herbal-cosmetics",
    name: "Pena za intimnu higijenu - Siberian Wellness Herbal Cosmetics",
    brand: "Kozmetika Siberian Wellness Herbal Cosmetics",
    categorySlugs: ["kozmetika-siberian-wellness-herbal-cosmetics"],
    shortDescription:
      "Pena za intimnu higijenu – Siberian Wellness Herbal Cosmetics sa kompleksom biljnih ekstrakata nežno čisti i neguje intimnu zonu.",
    image: "/products/pena-za-intimnu-higijenu-siberian-wellness-herbal-cosmetics.png",
    price: 1100,
  },
  {
    slug: "enzimski-piling-za-lice-siberian-wellness-herbal-cosmetics",
    name: "Enzimski piling za lice - Siberian Wellness Herbal Cosmetics",
    brand: "Kozmetika Siberian Wellness Herbal Cosmetics",
    categorySlugs: ["kozmetika-siberian-wellness-herbal-cosmetics"],
    shortDescription:
      "Enzimski piling za lice – Siberian Wellness Herbal Cosmetics podstiče blagi efekat pilinga. Ekstrakt nara, koji je bogat polifeonolima i vitaminima",
    image: "/products/enzimski-piling-za-lice-siberian-wellness-herbal-cosmetics.png",
    price: 1100,
  },
  {
    slug: "hidratantni-tonik-za-lice-siberian-wellness-herbal-cosmetics",
    name: "Hidratantni tonik za lice - Siberian Wellness Herbal Cosmetics",
    brand: "Kozmetika Siberian Wellness Herbal Cosmetics",
    categorySlugs: ["kozmetika-siberian-wellness-herbal-cosmetics"],
    shortDescription:
      "Hidratantni tonik za lice – Siberian Wellness Herbal Cosmetics sa hidrolatima hamamelisa, smilja i aminokiselinama dubinski hidrira, tonizira i omekšava kožu",
    image: "/products/hidratantni-tonik-za-lice-siberian-wellness-herbal-cosmetics.png",
    price: 990,
  },
  {
    slug: "matirajuci-tonik-za-lice-siberian-wellness-herbal-cosmetics",
    name: "Matirajući tonik za lice - Siberian Wellness Herbal Cosmetics",
    brand: "Kozmetika Siberian Wellness Herbal Cosmetics",
    categorySlugs: ["kozmetika-siberian-wellness-herbal-cosmetics"],
    shortDescription:
      "Matirajući tonik za lice – Siberian Wellness Herbal Cosmetics dubinski i nežno čisti pore, kontroliše nivo sebuma na površini kože",
    image: "/products/matirajuci-tonik-za-lice-siberian-wellness-herbal-cosmetics.png",
    price: 990,
  },
  {
    slug: "intimni-gel-siberian-wellness-herbal-cosmetics",
    name: "Intimni gel - Siberian Wellness Herbal Cosmetics",
    brand: "Kozmetika Siberian Wellness Herbal Cosmetics",
    categorySlugs: ["kozmetika-siberian-wellness-herbal-cosmetics"],
    shortDescription:
      "Intimni gel – Siberian Wellness Herbal Cosmetics nežni sapun brižljivo čisti osetljivu kožu intimne regije, pruža pouzdanu antibakterijsku zaštitu",
    image: "/products/intimni-gel-siberian-wellness-herbal-cosmetics.png",
    price: 1100,
  },
  {
    slug: "gel-za-ciscenje-lica-siberian-wellness-herbal-cosmetics",
    name: "Gel za čišćenje lica - Siberian Wellness Herbal Cosmetics",
    brand: "Kozmetika Siberian Wellness Herbal Cosmetics",
    categorySlugs: ["kozmetika-siberian-wellness-herbal-cosmetics"],
    shortDescription:
      "Gel za čišćenje lica – Siberian Wellness Herbal Cosmetics nežni penasti gel sa kompleksom biljnih ekstrakata i mlečne kiseline nežno čisti kožu",
    image: "/products/gel-za-ciscenje-lica-siberian-wellness-herbal-cosmetics.png",
    price: 1150,
  },
  {
    slug: "age-theraru-antioxidants-women-s-health",
    name: "Age Тhеrару Antioxidants - Women's Health",
    brand: "Women's Health",
    categorySlugs: [
      "womens-health",
      "anti-age-proizvode",
      "suplementi-za-zeludac-i-creva",
      "zdravo-srce",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Age Тhеrару Antioxidants – Women's Health kompleksan anti-age program sa najvažnijim antioksidansima za svakodnevnu podršku lepoti",
    image: "/products/age-theraru-antioxidants-women-s-health.png",
    price: 3500,
  },
  {
    slug: "methylfolate-women-s-health",
    name: "Methylfolate - Women's Health",
    brand: "Women's Health",
    categorySlugs: [
      "womens-health",
      "suplementi-za-trudnice-i-dojilje",
      "anti-age-proizvode",
      "zdravo-srce",
    ],
    shortDescription:
      "Methylfolate – Women's Health aktivni oblik folne kiseline Metafolin® od DSM Nutritional sa visokom biodostupnošću, odobren za upotrebu kod trudnica",
    image: "/products/methylfolate-women-s-health.png",
    price: 2900,
  },
  {
    slug: "d-manoza-i-severna-brusnica-women-s-health",
    name: "D-manoza i severna brusnica - Women's Health",
    brand: "Women's Health",
    categorySlugs: ["womens-health", "zdravi-bubrezi"],
    shortDescription:
      "D-manoza i severna brusnica – Women's Health prirodni uroprotektor na bazi D-manoze, ekstrakta brusnice, hibiskusa i medveđeg uva štiti bubrege",
    image: "/products/d-manoza-i-severna-brusnica-women-s-health.png",
    price: 3300,
  },
  {
    slug: "iron-bisglycinate-women-s-health",
    name: "Iron Bisglycinate - Women's Health",
    brand: "Women's Health",
    categorySlugs: ["womens-health", "anti-age-proizvode"],
    shortDescription:
      "Iron Bisglycinate – Women's Health gvožđe u biodostupnom helatnom obliku za prevenciju deficita gvožđa i podršku procesima stvaranja krvi",
    image: "/products/iron-bisglycinate-women-s-health.png",
    price: 2500,
  },
  {
    slug: "hijaluronska-kiselina-i-prirodni-vitamin-c-women-s-health",
    name: "Hijaluronska kiselina i prirodni vitamin C - Women's Health",
    brand: "Women's Health",
    categorySlugs: [
      "womens-health",
      "anti-age-proizvode",
      "duga-mladost",
    ],
    shortDescription:
      "Hijaluronska kiselina i prirodni vitamin C – Women's Health Beauty-kompleks sa hijaluronskom kiselinom i prirodnim vitaminom C",
    image: "/products/hijaluronska-kiselina-i-prirodni-vitamin-c-women-s-health.png",
    price: 6200,
  },
  {
    slug: "essential-botanics-bioavailable-curcumin",
    name: "Essential Botanics - Bioavailable Curcumin",
    brand: "Essential Botanics",
    categorySlugs: [
      "essential-botanics",
      "anti-age-proizvode",
      "suplementi-za-zeludac-i-creva",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Essential Botanics – Bioavailable Curcumin savremeno prirodno rešenje za zaštitu od upala. Inovativna formula C3® Reduct omogućava brzo apsorbovanje",
    image: "/products/essential-botanics-bioavailable-curcumin.png",
    price: 1590,
  },
  {
    slug: "essential-botanics-plant-derived-melatonin",
    name: "Essential Botanics - Plant - Derived Melatonin",
    brand: "Essential Botanics",
    categorySlugs: ["essential-botanics", "celicni-nervi", "antistres-zastita"],
    shortDescription:
      "Essential Botanics – Plant – Derived Melatonin je neophodna komponenta za zdrav, čvrst san i harmonično funkcionisanje nervnog sistema.",
    image: "/products/essential-botanics-plant-derived-melatonin.png",
    price: 890,
  },
  {
    slug: "essential-vitamins-vitamin-k2",
    name: "Essential Vitamins - Vitamin K2",
    brand: "Essential Vitamins",
    categorySlugs: [
      "essential-vitamins",
      "zdravo-srce",
      "anti-age-proizvode",
      "cvrste-kosti",
    ],
    shortDescription:
      "Essential Vitamins - Vitamin K2 biološki dostupan oblik vitamina K2, MenaQ7® pruža podršku zdravlju kardiovaskularnog i mišićno-koštanog sistema",
    image: "/products/essential-vitamins-vitamin-k2.png",
    price: 1990,
  },
  {
    slug: "siberian-super-natural-nutrition-eco-neurovision",
    name: "Siberian Super Natural Nutrition - ECO. Neurovision",
    brand: "Siberian Super Natural Nutrition",
    categorySlugs: ["siberian-super-natural-nutrition", "anti-age-proizvode"],
    shortDescription:
      "Siberian Super Natural Nutrition - ECO. Neurovision inovativni program za aktivan rad mozga i očuvanje vida, sada dostupan u novom, eko pakovanju.",
    image: "/products/siberian-super-natural-nutrition-eco-neurovision.png",
    price: 11300,
  },
  {
    slug: "siberian-super-natural-nutrition-eco-natural-vitamins",
    name: "Siberian Super Natural Nutrition - ECO. Natural Vitamins",
    brand: "Siberian Super Natural Nutrition",
    categorySlugs: ["siberian-super-natural-nutrition", "anti-age-proizvode"],
    shortDescription:
      "Siberian Super Natural Nutrition - ECO. Natural Vitamins vitamini, minerali i omega-3 kiseline: prirodna podrška telu u ekološkom pakovanju.",
    image: "/products/siberian-super-natural-nutrition-eco-natural-vitamins.png",
    price: 9900,
  },
  {
    slug: "siberian-super-natural-nutrition-eco-stress-re-live",
    name: "Siberian Super Natural Nutrition - ECO. Stress Re.Live",
    brand: "Siberian Super Natural Nutrition",
    categorySlugs: [
      "siberian-super-natural-nutrition",
      "antistres-zastita",
      "celicni-nervi",
      "anti-age-proizvode",
    ],
    shortDescription:
      "Siberian Super Natural Nutrition - ECO. Stress Re.Live Inovativni organski kompleksi za zaštitu nervnog sistema i sprečavanje stresa",
    image: "/products/siberian-super-natural-nutrition-eco-stress-re-live.png",
    price: 10300,
  },
  {
    slug: "siberian-super-natural-nutrition-eco-detox-pro-active",
    name: "Siberian Super Natural Nutrition - ECO. Detox Pro.Active",
    brand: "Siberian Super Natural Nutrition",
    categorySlugs: [
      "siberian-super-natural-nutrition",
      "detoks-i-ciscenje-organizma",
      "anti-age-proizvode",
      "suplementi-za-zeludac-i-creva",
      "suplementi-za-jetru",
    ],
    shortDescription:
      "Siberian Super Natural Nutrition - ECO. Detox Pro.Active profesionalni sistem unutrašnje kontrole detoksikacije i sveobuhvatnog čišćenja organizma",
    image: "/products/siberian-super-natural-nutrition-eco-detox-pro-active.png",
    price: 11300,
  },
  {
    slug: "men-s-power-maca-zinc-l-carnitine-fitness-catalist",
    name: "MEN'S POWER Maca+Zinc+L-Carnitine - Fitness Catalist",
    brand: "Fitness Catalyst",
    categorySlugs: [
      "fitness-catalyst",
      "suplementi-za-muskarce",
      "suplementi-za-energiju-i-fokus",
      "duga-mladost",
    ],
    shortDescription:
      "MEN'S POWER Maca+Zinc+L-Carnitine – Fitness Catalist muška formula za očuvanje seksualnog potencijala, snage i energije",
    image: "/products/men-s-power-maca-zinc-l-carnitine-fitness-catalist.png",
    price: 3950,
  },
  {
    slug: "taurin-fitness-catalist",
    name: "Таurin - Fitness Catalist",
    brand: "Fitness Catalyst",
    categorySlugs: ["fitness-catalyst", "anti-age-proizvode"],
    shortDescription:
      "Таurin - Fitness Catalist moćni aktivator antioksidantne zaštite. Povećava otpornost ćelijskih membrana na uticaj slobodnih radikala",
    image: "/products/taurin-fitness-catalist.png",
    price: 1100,
  },
  {
    slug: "energetski-booster-fitness-catalist",
    name: "Energetski Booster - Fitness Catalist",
    brand: "Fitness Catalyst",
    categorySlugs: ["fitness-catalyst"],
    shortDescription:
      "Energetski Booster - Fitness Catalist s zasićenim ukusom čokolade - tvoj pratilac u svet divnih utisaka! Inovativni ženšen Cereboost™ snabdeva mozak energijom",
    image: "/products/energetski-booster-fitness-catalist.png",
    price: 1950,
  },
  {
    slug: "essential-fatty-acids-siberian-linseed-oil-i-omega-3",
    name: "Essential Fatty Acids - Siberian Linseed Oil&Omega-3",
    brand: "Essential Fatty Acids",
    categorySlugs: [
      "essential-fatty-acids",
      "suplementi-za-energiju-i-fokus",
      "duga-mladost",
      "zdravo-srce",
    ],
    shortDescription:
      "Essential Fatty Acids - Siberian Linseed Oil&Omega-3 koncentrat obogaćen vitaminom E za vašu svakodnevnu ishranu.",
    image: "/products/essential-fatty-acids-siberian-linseed-oil-i-omega-3.png",
    price: 1600,
  },
  {
    slug: "dino-vision-chewable-tablets-with-blueberry-and-carotenoids-vitamama",
    name: "Dino Vision Chewable Tablets with Blueberry and Carotenoids - Vitamama",
    brand: "Vitamama",
    categorySlugs: ["vitamama", "suplementi-za-vid"],
    shortDescription:
      "Dino Vision Chewable Tablets with Blueberry and Carotenoids - Vitamama tablete sa antioksidansima, karotenoidima i svetlosnim filterima štite mrežnjaču",
    image: "/products/dino-vision-chewable-tablets-with-blueberry-and-carotenoids-vitamama.png",
    price: 1500,
  },
  {
    slug: "dino-vitamino-syrup-with-vitamins-and-minerals-vitamama",
    name: "Dino Vitamino Syrup with Vitamins and Minerals - Vitamama",
    brand: "Vitamama",
    categorySlugs: ["vitamama", "suplementi-za-imunitet"],
    shortDescription:
      "Dino Vitamino Syrup with Vitamins and Minerals - Vitamama voćni sirup s vitaminima i mineralnim materijama za rast i normalan razvoj dečjeg organizma.",
    image: "/products/dino-vitamino-syrup-with-vitamins-and-minerals-vitamama.png",
    price: 1550,
  },
  {
    slug: "imunotops-vocne-tablete-za-zvakanje-sa-vitaminima-a-c-i-d-vitamama",
    name: "Imunotops voćne tablete za žvakanje sa vitaminima A, C i D - Vitamama",
    brand: "Vitamama",
    categorySlugs: ["vitamama", "suplementi-za-imunitet"],
    shortDescription:
      "Imunotops voćne tablete za žvakanje sa vitaminima A, C i D - Vitamama tri glavna vitamina za rast i imunitet!",
    image: "/products/imunotops-vocne-tablete-za-zvakanje-sa-vitaminima-a-c-i-d-vitamama.png",
    price: 1400,
  },
  {
    slug: "dino-lactino-pektinski-sorbent-vitamama",
    name: "Dino Lactino Pektinski Sorbent - Vitamama",
    brand: "Vitamama",
    categorySlugs: ["vitamama"],
    shortDescription:
      "Dino Lactino Pektinski Sorbent - Vitamama najbolji prijatelj malenih stomaka će priskočiti u pomoć u svakom trenutku!",
    image: "/products/dino-lactino-pektinski-sorbent-vitamama.png",
    price: 1500,
  },
  {
    slug: "corenrg-antioksidantni-booster",
    name: "CoreNRG Antioksidantni Booster",
    brand: "CoreNRG",
    categorySlugs: ["corenrg", "anti-age-proizvode"],
    shortDescription:
      "CoreNRG Antioksidantni Booster sočni koktel ispunjen snagom sunčanog kurkumina - najjači antioksidans, koji pruža moćan anti-age efekat.",
    image: "/products/corenrg-antioksidantni-booster.jpg",
    price: 1700,
  },
  {
    slug: "greenpin-sredstvo-za-pranje",
    name: "GreenPin sredstvo za pranje",
    brand: "GreenPin",
    categorySlugs: ["greenpin"],
    shortDescription:
      "GreenPin sredstvo za pranje  inovativno univerzalno sredstvo za pranje prirodnih i sintetičkih tkanina, a takođe i tkanina od mešanih vlakana.",
    image: "/products/greenpin-sredstvo-za-pranje.png",
    price: 2700,
  },
  {
    slug: "extra-rich-massage-balsam-koren-280ml",
    name: "Extra Rich Massage Balsam Koren 280ml",
    brand: "Sibirski balzami",
    categorySlugs: ["sibirski-balzami"],
    shortDescription:
      "Extra Rich Massage Balsam Koren 280ml koji deluje zagrevajuće i opuštajuće sa veličanstvenom aromom, je jedinstven i veoma efikasan kompleks",
    image: "/products/extra-rich-massage-balsam-koren-280ml.png",
    price: 1250,
  },
  {
    slug: "hidratantni-regenerator-za-kosu-siberian-wellness",
    name: "Hidratantni regenerator za kosu - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Hidratantni regenerator za kosu - Siberian Wellness hidrira i štiti od oštećenja, poklanja kosi volumen i elastičnost, čini je sjajnom i snažnom.",
    image: "/products/hidratantni-regenerator-za-kosu-siberian-wellness.png",
    price: 1200,
  },
  {
    slug: "volumizing-hair-conditioner-siberian-wellness",
    name: "Volumizing Hair Conditioner - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Volumizing Hair Conditioner - Siberian Wellness regenerator sa sukcinskom kiselinom i biljnim proteinima povećava volumen i smanjuje krtost vlasi",
    image: "/products/volumizing-hair-conditioner-siberian-wellness.png",
    price: 1200,
  },
  {
    slug: "dry-and-solored-hair-sonditioner-siberian-wellness",
    name: "Dry and Сolored Hair Сonditioner - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Dry and Сolored Hair Сonditioner - Siberian Wellness efikasni regenerator sa ceramidama i biljnim keratinom obnavlja oštećenu kosu i farbanu kosu",
    image: "/products/dry-and-solored-hair-sonditioner-siberian-wellness.png",
    price: 1200,
  },
  {
    slug: "ekstra-bogata-biljna-pasta-za-izbeljivanje-zuba",
    name: "Ekstra bogata biljna pasta za izbeljivanje zuba",
    brand: "Paste za zube",
    categorySlugs: ["paste-za-zube"],
    shortDescription:
      "Ekstra bogata biljna pasta za izbeljivanje zuba crna pasta za zube za snežno beli osmeh! Ova ultra bogata pasta za zube na biljnoj bazi sa drvenim ugljem",
    image: "/products/ekstra-bogata-biljna-pasta-za-izbeljivanje-zuba.png",
    price: 750,
  },
  {
    slug: "spiced-punch-hranljivi-losion-za-telo-siberian-wellness",
    name: "Spiced Punch hranljivi losion za telo - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Spiced Punch hranljivi losion za telo - Siberian Wellness s aktivnim kompleksom ulja, alantoinom i D-pantenolom omekšava i hidrira kožu",
    image: "/products/spiced-punch-hranljivi-losion-za-telo-siberian-wellness.png",
    price: 1150,
  },
  {
    slug: "spiced-punch-hranljivi-gel-za-tusiranje-siberian-wellness",
    name: "Spiced Punch hranljivi gel za tuširanje - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Spiced Punch hranljivi gel za tuširanje - Siberian Wellness formula s biljnim ekstraktima i inulinom blago čisti, hidrira i hrani kožu.",
    image: "/products/spiced-punch-hranljivi-gel-za-tusiranje-siberian-wellness.png",
    price: 790,
  },
  {
    slug: "spiced-punch-hranljiva-krema-puter-za-telo-siberian-wellness",
    name: "Spiced Punch hranljiva krema-puter za telo - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Spiced Punch hranljiva krema-puter za telo - Siberian Wellness formula s prirodnim emulgatorom na bazi etra voska jojobe, pčelinjeg voska",
    image: "/products/spiced-punch-hranljiva-krema-puter-za-telo-siberian-wellness.png",
    price: 1900,
  },
  {
    slug: "essential-sorbents-pure-life",
    name: "Essential Sorbents - Pure Life",
    brand: "Essential Sorbents",
    categorySlugs: [
      "essential-sorbents-lymphosan",
      "detoks-i-ciscenje-organizma",
      "suplementi-za-zeludac-i-creva",
      "prevencija-alergija",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Essential Sorbents - Pure Life detox - koktel na bazi prirodnih fitosorbenata podstiče efikasno i nežno čišćenje organizma od toksina",
    image: "/products/essential-sorbents-pure-life.png",
    price: 1400,
  },
  {
    slug: "siberian-super-natural-nutrition-eco-beautysense",
    name: "Siberian Super Natural Nutrition - ECO. BeautySense",
    brand: "Siberian Super Natural Nutrition",
    categorySlugs: [
      "siberian-super-natural-nutrition",
      "anti-age-proizvode",
      "duga-mladost",
    ],
    shortDescription:
      "Siberian Super Natural Nutrition - ECO. BeautySense nutrikozmetički anti-age sistem za očuvanje mladalačkog izgleda kože u novom ekološkom pakovanju.",
    image: "/products/siberian-super-natural-nutrition-eco-beautysense.png",
    price: 11900,
  },
  {
    slug: "immunotops-hrskave-kuglice-sa-inulinom-visnja-vitamama",
    name: "Immunotops hrskave kuglice sa inulinom višnja - Vitamama",
    brand: "Vitamama",
    categorySlugs: ["vitamama"],
    shortDescription:
      "Immunotops hrskave kuglice sa inulinom višnja - Vitamama ukusan izvor vitamina C, vlakana i odličnog raspoloženja!",
    image: "/products/immunotops-hrskave-kuglice-sa-inulinom-visnja-vitamama.png",
    price: 1150,
  },
  {
    slug: "koenzim-q10-expert-line",
    name: "Koenzim Q10 - Expert Line",
    brand: "Expert Line",
    categorySlugs: ["expert-line", "zdravo-srce", "anti-age-proizvode"],
    shortDescription:
      "Biodostupni Koenzim Q10 štiti srce i krvne sudove od procesa starenja, povećava energetski potencijal ćelija i održava lepotu kože i kose.",
    image: "/products/koenzim-q10-expert-line.png",
    price: 2500,
  },
  {
    slug: "magnesium-multi-chelate-expert-line",
    name: "Magnesium Multi-Chelate - Expert Line",
    brand: "Expert Line",
    categorySlugs: [
      "expert-line",
      "celicni-nervi",
      "anti-age-proizvode",
      "antistres-zastita",
      "suplementi-za-zeludac-i-creva",
      "zdravo-srce",
      "prevencija-dijabetesa",
    ],
    shortDescription:
      "Magnesium Multi-Chelate - Expert Line u bioraspoloživim oblicima pomaže u smanjenju nervne napetosti i vraćanju emocionalne ravnoteže",
    image: "/products/magnesium-multi-chelate-expert-line.png",
    price: 2400,
  },
  {
    slug: "s-acetyl-l-glutathione-expert-line",
    name: "S-Acetyl-L-Glutathione - Expert Line",
    brand: "Expert Line",
    categorySlugs: ["expert-line", "anti-age-proizvode", "detoks-i-ciscenje-organizma"],
    shortDescription:
      "Lako usvojiv S-acetil-L-Glutation usporava proces starenja i jača odbrambene snage organizma. Delujući kao moćan antioksidans",
    image: "/products/s-acetyl-l-glutathione-expert-line.png",
    price: 4900,
  },
  {
    slug: "mama-box-trudnoca",
    name: "MAMA Box - Trudnoća",
    brand: "Daily Box",
    categorySlugs: ["daily-box", "suplementi-za-trudnice-i-dojilje"],
    shortDescription:
      "MAMA Box - Trudnoća kompleksan program sa prirodnim vitaminima, bioraspoloživim L-metilfolatom, mineralima i omega-3 polinezasićenim kiselinama.",
    image: "/products/mama-box-trudnoca.jpg",
    price: 4950,
  },
  {
    slug: "hranljiva-krema-za-telo-siberian-wellness",
    name: "Hranljiva krema za telo – Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Hranljiva krema za telo – Siberian Wellness s uljem pasjeg trna, hidrolatima i biljnim ekstraktima intenzivno hrani kožu, čuva lipidni balans",
    image: "/products/hranljiva-krema-za-telo-siberian-wellness.png",
    price: 1200,
  },
  {
    slug: "hidratantna-krema-za-telo-siberian-wellness",
    name: "Hidratantna krema za telo – Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Hidratantna krema za telo – Siberian Wellness s ekstraktom sibirskog bilja neguje kožu i podstiče obnavljanje epidermalne barijere",
    image: "/products/hidratantna-krema-za-telo-siberian-wellness.png",
    price: 1200,
  },
  {
    slug: "hidratantni-gel-za-tusiranje-siberian-wellness",
    name: "Hidratantni gel za tuširanje – Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Hidratantni gel za tuširanje – Siberian Wellness sa sibirskim biljem – prirodno sredstvo za čišćenje za svaki dan.",
    image: "/products/hidratantni-gel-za-tusiranje-siberian-wellness.png",
    price: 790,
  },
  {
    slug: "serum-za-rast-kose-siberian-wellness",
    name: "Serum za rast kose – Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Serum za rast kose – Siberian Wellness inovativna formula sa aminokiselinama i biljnim kompleksom Baicapil™ deluje protiv opadanja kose",
    image: "/products/serum-za-rast-kose-siberian-wellness.png",
    price: 2800,
  },
  {
    slug: "krema-za-masnu-kozu-sklonu-aknama-siberian-wellness",
    name: "Krema za masnu kožu sklonu aknama - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Krema za masnu kožu sklonu aknama - Siberian Wellness sa bioraspoloživim sumporom i ekstraktom magnolije smanjuje izražene nesavršenosti",
    image: "/products/krema-za-masnu-kozu-sklonu-aknama-siberian-wellness.png",
    price: 1700,
  },
  {
    slug: "obnavljajuca-esencija-s-niacinamidom-10-experalta-platinum",
    name: "Obnavljajuća esencija s niacinamidom 10% – Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Zahvaljujući specijalnoj formuli Obnavljajuća esencija s niacinamidom 10% – Experalta Platinum podstiče vidljivo smanjenje bora i tankih linija",
    image: "/products/obnavljajuca-esencija-s-niacinamidom-10-experalta-platinum.png",
    price: 1900,
  },
  {
    slug: "revitalizing-plant-peptides-night-cream-experalta-platinum",
    name: "Revitalizing plant peptides night cream – Experalta Platinum",
    brand: "Kozmetika Experalta Platinum",
    categorySlugs: ["kozmetika-experalta-platinum"],
    shortDescription:
      "Revitalizing plant peptides night cream – Experalta Platinum je intenzivna krema koja obnavlja i hidrira kožu tokom noći.",
    image: "/products/revitalizing-plant-peptides-night-cream-experalta-platinum.png",
    price: 2990,
  },
  {
    slug: "greenpin-vlazne-maramice-za-ciscenje",
    name: "GreenPin vlažne maramice za čišćenje",
    brand: "GreenPin",
    categorySlugs: ["greenpin"],
    shortDescription:
      "GreenPin vlažne maramice za čišćenje će Vam pomoći da pobedite veliku prljavštinu, skinete fleke i neprijatne mirise.",
    image: "/products/greenpin-vlazne-maramice-za-ciscenje.png",
    price: 490,
  },
  {
    slug: "hranljivi-gel-za-tusiranje-siberian-wellness",
    name: "Hranljivi gel za tuširanje - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "Hranljivi gel za tuširanje - Siberian Wellness s uljem zlolesine brižljivo čisti i intenzivno hrani kožu, čuva lipidni balans",
    image: "/products/hranljivi-gel-za-tusiranje-siberian-wellness.png",
    price: 790,
  },
  {
    slug: "all-in-one-anti-aging-treatment-siberian-wellness",
    name: "All-In-One Anti-Aging Treatment - Siberian Wellness",
    brand: "Kozmetika Siberian Wellness",
    categorySlugs: ["kozmetika-siberian-wellness"],
    shortDescription:
      "All-In-One Anti-Aging Treatment - Siberian Wellness hranljiva krema pruža finu negu zrele kože, obnavlja je i hidrira.",
    image: "/products/all-in-one-anti-aging-treatment-siberian-wellness.png",
    price: 1700,
  },
  {
    slug: "tree-mushroom-complex-essential-botanics",
    name: "Tree Mushroom Complex - Essential Botanics",
    brand: "Essential Botanics",
    categorySlugs: [
      "essential-botanics",
      "suplementi-za-imunitet",
      "anti-age-proizvode",
      "suplementi-za-jetru",
      "zdravo-srce",
    ],
    shortDescription:
      "Tree Mushroom Complex - Essential Botanics dodatak ishrani sa četiri vrste gljiva ( čaga, šiitake, reiši i maitake ) namenjen je nutritivnoj podršci imunitetu",
    image: "/products/tree-mushroom-complex-essential-botanics.png",
    price: 2400,
  },
  {
    slug: "lion-s-mane-i-cordyceps-essential-botanics",
    name: "Lion's Mane & Cordyceps - Essential Botanics",
    brand: "Essential Botanics",
    categorySlugs: [
      "essential-botanics",
      "suplementi-za-energiju-i-fokus",
      "anti-age-proizvode",
      "antistres-zastita",
      "suplementi-za-imunitet",
    ],
    shortDescription:
      "Lion's Mane & Cordyceps - Essential Botanics dodatak ishrani sa ekstraktima lavlje grive, kordicepsa i L-lizina, namenjen podršci mentalnoj aktivnosti, fokusu",
    image: "/products/lion-s-mane-i-cordyceps-essential-botanics.png",
    price: 3600,
  },
  {
    slug: "lutein-i-zeaxanthin-essential-fatty-acids",
    name: "Lutein & Zeaxanthin - Essential Fatty Acids",
    brand: "Essential Fatty Acids",
    categorySlugs: [
      "essential-fatty-acids",
      "suplementi-za-vid",
      "suplementi-za-energiju-i-fokus",
      "duga-mladost",
    ],
    shortDescription:
      "Lutein & Zeaxanthin - Essential Fatty Acids biljni kompleks sa prirodnim svetlosnim filterima – luteinom i zeaksantinom – štiti mrežnjaču oka",
    image: "/products/lutein-i-zeaxanthin-essential-fatty-acids.png",
    price: 2300,
  },
  {
    slug: "piling-za-telo-forest-dreams",
    name: "Piling za telo - Forest Dreams",
    brand: "Kozmetika Forest Dreams",
    categorySlugs: ["kozmetika-forest-dreams"],
    shortDescription:
      "Piling za telo - Forest Dreams zahvaljujući nežnoj teksturi piling fino skida izumrle ćelije, poklanja koži prirodan sjaj i glatkoću.",
    image: "/products/piling-za-telo-forest-dreams.png",
    price: 1600,
  },
  {
    slug: "buter-krema-za-telo-forest-dreams",
    name: "Buter krema za telo – Forest Dreams",
    brand: "Kozmetika Forest Dreams",
    categorySlugs: ["kozmetika-forest-dreams"],
    shortDescription:
      "Buter krema za telo – Forest Dreams, hrani i hidrira kožu, poklanjajući joj mek i gladak izgled.",
    image: "/products/buter-krema-za-telo-forest-dreams.png",
    price: 2000,
  },
  {
    slug: "gel-za-tusiranje-forest-dreams",
    name: "Gel za tuširanje - Forest Dreams",
    brand: "Kozmetika Forest Dreams",
    categorySlugs: ["kozmetika-forest-dreams"],
    shortDescription:
      "Gel za tuširanje - Forest Dreams blago čisti kožu. Nežna aroma poklanja osećaj svežine i bodrosti, kao dašak prohladnog šumskog jutra!",
    image: "/products/gel-za-tusiranje-forest-dreams.png",
    price: 800,
  },
  {
    slug: "fito-caj-od-divljeg-bilja-11-energija-i-vitalnost",
    name: "Fito čaj od divljeg bilja №11 – Energija i vitalnost",
    brand: "Kolekcija fitočajeva",
    categorySlugs: ["kolekcija-fitocajeva", "antistres-zastita"],
    shortDescription:
      "Fito čaj od divljeg bilja №11 – Energija i vitalnost pravi tajga ukus i aroma – bez kofeina i veštačkih dodataka.",
    image: "/products/fito-caj-od-divljeg-bilja-11-energija-i-vitalnost.png",
    price: 830,
  },
  {
    slug: "fito-caj-od-divljeg-bilja-10-podrska-bubrezima",
    name: "Fito čaj od divljeg bilja №10 - Podrška bubrezima",
    brand: "Kolekcija fitočajeva",
    categorySlugs: ["kolekcija-fitocajeva", "zdravi-bubrezi"],
    shortDescription:
      "Fito čaj od divljeg bilja №10 - Podrška bubrezima kompleksna biljna mešavina, list medveđeg grožđa i brusnice, šipurak, kopriva i kantarion",
    image: "/products/fito-caj-od-divljeg-bilja-10-podrska-bubrezima.png",
    price: 699,
  },
  {
    slug: "ultra-zasicena-krema-za-lice-experalta-pro",
    name: "Ultra zasićena krema za lice - Experalta Pro",
    brand: "Kozmetika Experalta Pro",
    categorySlugs: ["kozmetika-experalta-pro"],
    shortDescription:
      "Ultra zasićena krema za lice sa bogatom teksturom poboljšava mikroreljef kože: konture lica postaju jasnije, ten je ujednačen.",
    image: "/products/ultra-zasicena-krema-za-lice-experalta-pro.png",
    price: 6200,
  },
  {
    slug: "totalni-serum-lepote-experalta-pro",
    name: "Totalni serum lepote - Experalta Pro",
    brand: "Kozmetika Experalta Pro",
    categorySlugs: ["kozmetika-experalta-pro"],
    shortDescription:
      "Totalni serum lepote - Experalta Pro za intenzivno hidriranje snabdeva ćelije kože energijom, sistemski podržava njihov rad",
    image: "/products/totalni-serum-lepote-experalta-pro.png",
    price: 6200,
  },
];
